### ISSUE TITLE
Надо удалить .DS_Store, я себе WebStorm сломал. 

### ISSUE THREAD

**Issue by Mootfrost777** [PavlychevV/Chelyabinsk#1]
Я все в названии написал.

**Comment by PavlychevV** [comment]
Этот файл кэша нельзя удалить, так устроена macOS. Он создаётся автоматически. Обычному пользователю он не виден, а тот, у кого включены скрытые файлы, может удалить его с лёгкостью.

**Comment by Mootfrost777** [comment]
Ну единственным правильным решением было бы создание .gitignore. Этот файл нигде в программе не используется, только, как оказалось, ломает WebStorm при мисклике

**Comment by PavlychevV** [comment]
А ты не мискликай. У меня не ломает и .gitignore не поможет при создании релиза, могу только в ветке удалить.
